name = "hicks-consulting-canonical"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-02"

[vars]
TRAINING_INQUIRY_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbx7TneKS_mq6eJfcBpSxtzhgUzgjubYXKw5i8BAeisz7Z0YilvqVjOWdbwBAVqbYKtj/exec"
TRAINING_INQUIRY_SECRET = "gjV0T-nKsFcO00DH2z94LWpc7CpQkEalonZBqEgiH2DFFv5SAOyx39RRFqmfq2Op"
