import { readJson, writeJsonAtomic, nowIso } from '../autonomy/lib/io.mjs';
function gscRows(){const g=readJson('data/agency/gsc_snapshot.json',{});return Array.isArray(g.queryPage)?g.queryPage:[];}
function rowQuery(r){return String(r?.keys?.[0]||'').toLowerCase();}
function pathFrom(v){try{return new URL(v).pathname}catch{return String(v||'')}}
export function buildSearchActionQueue(clock=new Date()){
 const observations=readJson('data/search/query_observations.json',{observations:[]});const targets=readJson('data/search/target_queries.json',{queries:[]});const rows=gscRows();const items=[];
 for(const target of targets.queries){const obs=(observations.observations||[]).find(x=>x.query.toLowerCase()===target.query.toLowerCase());const g=rows.filter(r=>rowQuery(r)===target.query.toLowerCase());const impressions=g.reduce((a,r)=>a+Number(r.impressions||0),0),clicks=g.reduce((a,r)=>a+Number(r.clicks||0),0);const positions=g.map(r=>Number(r.position||0)).filter(Boolean);const avg=positions.length?positions.reduce((a,b)=>a+b,0)/positions.length:0;const rankingPages=[...new Set(g.map(r=>pathFrom(r?.keys?.[1]||'')).filter(Boolean))];let status='UNKNOWN';const reasons=[];if(obs?.status==='provider_error')status='PROVIDER_ERROR';else if(obs?.siteSurfaced||impressions>0)status='OBSERVED';else if(obs?.status==='ok')status='MISSING';if(rankingPages.length>1){status='CANNIBALIZATION_REVIEW';reasons.push('MULTIPLE_HICKS_PAGES_FOR_QUERY');}if(rankingPages.length===1&&rankingPages[0]!==target.primaryPage){status='WRONG_PAGE';reasons.push('WRONG_HICKS_PAGE_RANKING');}if(impressions>=20&&clicks===0)reasons.push('IMPRESSIONS_WITHOUT_CLICKS');if(avg>10)reasons.push('AVERAGE_POSITION_OUTSIDE_TOP_10');for(const d of obs?.diagnosis||[])reasons.push(d);
 const safeRepairEligible=['MISSING','WRONG_PAGE'].includes(status)&&obs?.status==='ok';items.push({query:target.query,primaryPage:target.primaryPage,status,reasons:[...new Set(reasons)],evidence:{groundedSiteSurfaced:obs?.status==='ok'?Boolean(obs.siteSurfaced):null,groundedProviderAnswered:obs?.status==='ok',gscImpressions:impressions,gscClicks:clicks,gscAveragePosition:Number(avg.toFixed(2)),gscPages:rankingPages,competitorUrls:(obs?.citations||[]).filter(c=>!String(c.url||'').includes('hicksconsulting.org')).slice(0,5)},safeRepairEligible,recommendedAction:safeRepairEligible?'Run bounded search-alignment repair, rebuild, then await the next external observation cycle.':'Observe or route to content/technical review; do not invent a ranking win.'});}
 const out={schemaVersion:'2.0.0',generatedAt:nowIso(clock),policy:'Hicks may autonomously apply bounded technical/search-alignment repairs. Substantive clinical claims and unsupported treatment assertions are never auto-generated from competitor content.',items};writeJsonAtomic('data/search/search_action_queue.json',out);return out;
}
if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(buildSearchActionQueue(),null,2));
