import fs from 'node:fs';
import path from 'node:path';
import { readJson, writeJsonAtomic, nowIso, routeToSourceFile } from '../autonomy/lib/io.mjs';

const SITE_HOST='hicksconsulting.org';
function cleanText(v){return String(v||'').replace(/\s+/g,' ').trim();}
function hostOf(u){try{return new URL(u).hostname.replace(/^www\./,'').toLowerCase();}catch{return '';}}
function attributedHost(c){const title=String(c?.title||'').trim().toLowerCase().replace(/^www\./,'');if(/^[a-z0-9.-]+\.[a-z]{2,}$/.test(title))return title;return hostOf(c?.url||'');}function isSiteCitation(c){const h=attributedHost(c);return h===SITE_HOST||h.endsWith('.'+SITE_HOST)||String(c?.title||'').toLowerCase().includes(SITE_HOST);}
function stripHtml(html){return cleanText(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' '));}
function ownPageFeatures(route){const rel=routeToSourceFile(route);const full=path.resolve(process.cwd(),rel);if(!fs.existsSync(full))return {route,sourceFile:rel,status:'missing'};const html=fs.readFileSync(full,'utf8');const pick=(re)=>cleanText((html.match(re)||[])[1]||'');return {route,sourceFile:rel,status:'ok',title:pick(/<title[^>]*>([\s\S]*?)<\/title>/i),description:pick(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i)||pick(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i),h1:pick(/<h1[^>]*>([\s\S]*?)<\/h1>/i),textChars:stripHtml(html).length,internalLinks:(html.match(/href=["']\//g)||[]).length,canonical:pick(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)/i)};}
async function fetchFeature(url){try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 HicksSearchHealth/1.0'},redirect:'follow',signal:AbortSignal.timeout(12000)});const html=await r.text();if(!r.ok)return {url,status:'http_error',httpStatus:r.status};const pick=(re)=>cleanText((html.match(re)||[])[1]||'');return {url,resolvedUrl:r.url,status:'ok',httpStatus:r.status,title:pick(/<title[^>]*>([\s\S]*?)<\/title>/i),h1:pick(/<h1[^>]*>([\s\S]*?)<\/h1>/i),headings:[...html.matchAll(/<h[2-3][^>]*>([\s\S]*?)<\/h[2-3]>/gi)].slice(0,20).map(m=>stripHtml(m[1])),textChars:stripHtml(html).length};}catch(e){return {url,status:'fetch_failed',error:e.message};}}
function geminiParts(body){const c=body?.candidates?.[0]||{};const text=(c.content?.parts||[]).map(p=>p.text||'').join('\n');const gm=c.groundingMetadata||{};const chunks=(gm.groundingChunks||[]).map(x=>x.web||x).filter(x=>x&&x.uri).map(x=>({url:x.uri,title:x.title||''}));return {text,searchQueries:gm.webSearchQueries||[],chunks};}
async function geminiObserve(query,primaryPage,env){const model=env.GEMINI_SEARCH_MODEL||'gemini-2.5-flash-lite';const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`;const prompt=`Use Google Search to investigate this exact local search query: ${JSON.stringify(query)}. We are evaluating https://www.hicksconsulting.org${primaryPage}. Identify which public web sources Google-grounded search uses for this query, whether Hicks Consulting is among the cited/surfaced sources, and the strongest competing pages or directories. Do not invent organic rank. Keep the answer factual and concise.`;const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],tools:[{google_search:{}}],generationConfig:{temperature:0.1}}),signal:AbortSignal.timeout(Number(env.GEMINI_SEARCH_TIMEOUT_MS||30000))});const text=await r.text();if(!r.ok)throw new Error(`${r.status}: ${text.slice(0,500)}`);const body=JSON.parse(text);return {model,...geminiParts(body)};}
function diagnosis(query,own,citations,siteSurfaced,competitors=[]){const q=query.toLowerCase();const combined=`${own.title||''} ${own.description||''} ${own.h1||''}`.toLowerCase();const reasons=[];if(own.status!=='ok')reasons.push('TARGET_PAGE_MISSING');if(!combined.includes(q))reasons.push('EXACT_QUERY_NOT_IN_PRIMARY_SEARCH_SURFACES');if((own.description||'').length<80)reasons.push('WEAK_META_DESCRIPTION');if((own.internalLinks||0)<3)reasons.push('WEAK_INTERNAL_AUTHORITY');if(!siteSurfaced)reasons.push('SITE_NOT_SURFACED_IN_GROUNDED_OBSERVATION');if(citations.length===0)reasons.push('NO_GROUNDED_CITATIONS_RETURNED');const healthy=competitors.filter(c=>c.status==='ok');if(healthy.some(c=>(c.textChars||0)>(own.textChars||0)*1.35))reasons.push('COMPETITOR_BROADER_VISIBLE_COVERAGE');if(healthy.some(c=>(c.headings||[]).length>8))reasons.push('COMPETITOR_DEEPER_ANSWER_STRUCTURE');return reasons;}
export async function runLiveQueryObservation(env=process.env,clock=new Date()){
 const targets=readJson('data/search/target_queries.json',{queries:[]});const configured=Boolean(env.GEMINI_API_KEY);const limit=Math.max(1,Math.min(25,Number(env.LIVE_QUERY_LIMIT||targets.queries.length||7)));const observations=[];
 if(configured){for(const target of targets.queries.slice(0,limit)){const own=ownPageFeatures(target.primaryPage);try{const g=await geminiObserve(target.query,target.primaryPage,env);const citations=g.chunks;const siteSurfaced=citations.some(isSiteCitation);const competitorCitations=citations.filter(c=>!isSiteCitation(c)).slice(0,5);const competitorFeatures=[];for(const item of competitorCitations.slice(0,3))competitorFeatures.push(await fetchFeature(item.url));observations.push({query:target.query,primaryPage:target.primaryPage,status:'ok',observedAt:nowIso(clock),provider:'gemini_google_search_grounding',model:g.model,observationType:'GROUNDED_WEB_SURFACING',rankVerified:false,siteSurfaced,citations,searchQueries:g.searchQueries,competitors:competitorFeatures,ownPage:own,diagnosis:diagnosis(target.query,own,citations,siteSurfaced,competitorFeatures)});}catch(e){observations.push({query:target.query,primaryPage:target.primaryPage,status:'provider_error',observedAt:nowIso(clock),provider:'gemini_google_search_grounding',rankVerified:false,error:e.message,ownPage:own,diagnosis:['PROVIDER_ERROR']});}}
 }
 const state=configured?(observations.some(x=>x.status==='ok')?'CONNECTED':'DEGRADED'):'NOT_CONFIGURED';const out={schemaVersion:'2.0.0',generatedAt:nowIso(clock),providerState:state,truthBoundary:'These are Google-Search-grounded web observations and citations. They are not literal organic SERP positions. Use GSC for Google-owned impressions, clicks, CTR, and average position.',observations};writeJsonAtomic('data/search/query_observations.json',out);
 const hist=readJson('data/search/query_observation_history.json',{schemaVersion:'1.0.0',observations:[]});hist.observations=[...(hist.observations||[]),...observations].slice(-1000);hist.updatedAt=nowIso(clock);writeJsonAtomic('data/search/query_observation_history.json',hist);return out;
}
if(import.meta.url===`file://${process.argv[1]}`)runLiveQueryObservation().then(x=>console.log(JSON.stringify({ok:true,providerState:x.providerState,observed:x.observations.length,surfaced:x.observations.filter(o=>o.siteSurfaced).length},null,2))).catch(e=>{console.error(e);process.exit(1)});
