#!/usr/bin/env node
import { validateDraft, localRepairDraft, SAFE_HARBOR_DECISIONS, plainTextFromDraft } from '../../../scripts/autonomy/lib/safe_harbor.mjs';
import { cadenceMatches, nextAvailableSlot } from '../../../scripts/autonomy/lib/cadence.mjs';
import { emitFinding } from '../../validation/protocol.js';
const errors=[];
const base={title:'Understanding emotional overload',description:'A practical educational guide to recognizing emotional overload and choosing grounded next steps.',shortAnswer:'Emotional overload can make ordinary decisions feel harder. A useful first step is to slow the pace, name what is happening, and choose one source of support.',sections:[{heading:'What this can look like',body:'Emotional overload may show up as irritability, difficulty concentrating, trouble resting, or feeling responsible for everything. These experiences can have many causes and do not create a diagnosis on their own. '.repeat(35),bullets:['Notice the pattern','Reduce one demand','Ask for support']}],sources:[],internalLinks:['/therapy/','/resources/'],disclaimer:'This educational resource does not provide diagnosis or individualized medical advice.'};
let result=validateDraft(base,{minimumWords:300}); if(result.decision!=='SAFE_AUTOPUBLISH')errors.push(`safe-draft:${result.decision}`);
const unsafe=structuredClone(base);unsafe.sections[0].body+=' This will cure anxiety and guarantee results.';result=validateDraft(unsafe,{minimumWords:300});if(result.decision!=='REPAIR_REQUIRED')errors.push(`repair-decision:${result.decision}`);const repaired=localRepairDraft(unsafe,result.findings);result=validateDraft(repaired,{minimumWords:300});if(!['SAFE_AUTOPUBLISH'].includes(result.decision))errors.push(`repair-failed:${result.decision}`);
const protectedDraft=structuredClone(base);protectedDraft.sections[0].body+=' The fee is $150 and appointments are available this week.';result=validateDraft(protectedDraft,{minimumWords:300});if(result.decision!=='SKIPPED_UNSUPPORTED_CLAIM')errors.push(`protected-fact:${result.decision}`);
result=validateDraft(base,{minimumWords:300,existingDocuments:[{route:'/existing/',text:plainTextFromDraft(base)}]});if(result.decision!=='SKIPPED_DUPLICATE_INTENT')errors.push(`duplicate:${result.decision}`);
if(!SAFE_HARBOR_DECISIONS.includes('SYSTEM_BLOCKED')||!SAFE_HARBOR_DECISIONS.includes('SKIPPED_PROTECTED_OWNER'))errors.push('decision-enum');
const manifest=[{id:'existing',contentType:'articles',scheduledAt:'2027-01-05T13:00:00.000Z'}];const slot=nextAvailableSlot('articles',manifest,'2027-01-06T00:00:00.000Z');if(!cadenceMatches('articles',slot))errors.push(`cadence-slot:${slot}`);
if(errors.length){emitFinding(errors);process.exit(1);}console.log('Safe Harbor behavior OK (safe publish, bounded repair, protected-fact skip, duplicate skip, and cadence-compliant scheduling proven with isolated fixtures).');
