const { fs, path, fail, exists, read } = require('./util');
const root = process.cwd();
const pkg = JSON.parse(read('package.json'));
const requiredScripts = ['indexnow:emit', 'indexnow:submit', 'gsc:reindex-queue', 'distribution:post-publish', 'validate:indexnow', 'validate:profile:indexnow'];
for (const script of requiredScripts) if (!pkg.scripts || !pkg.scripts[script]) fail(`IndexNow contract fail: package.json missing script ${script}`);
const requiredFiles = ['scripts/indexnow_emit.js','scripts/indexnow_submit.js','scripts/gsc_reindex_queue.js','scripts/distribution/run_post_publish_distribution.mjs','.github/workflows/indexnow-submit.yml'];
for (const file of requiredFiles) if (!exists(file)) fail(`IndexNow contract fail: missing ${file}`);
const build = read('scripts/site_build.js');
if (!/indexnow\.txt/.test(build)) fail('IndexNow contract fail: build must copy root indexnow.txt into dist for key verification.');
const workflow = read('.github/workflows/indexnow-submit.yml');
if (!/workflow_run:/.test(workflow) || !/workflows:\s*\["Content Publish"\]/.test(workflow)) fail('IndexNow contract fail: workflow must run only after Content Publish.');
if (!/github\.event\.workflow_run\.conclusion == 'success'/.test(workflow)) fail('IndexNow contract fail: workflow must require successful Content Publish conclusion.');
if (!/workflow_dispatch:/.test(workflow)) fail('IndexNow contract fail: workflow must support workflow_dispatch.');
for (const command of ['npm run build','npm run indexnow:emit','npm run distribution:post-publish','npm run validate:profile:indexnow','npm run validate:authority-modernization']) if (!workflow.includes(command)) fail(`IndexNow contract fail: workflow missing ${command}.`);
if (!/git add data\/distribution/.test(workflow)) fail('IndexNow contract fail: workflow must commit durable distribution receipts.');
if (!/actions\/upload-artifact@v4/.test(workflow)) fail('IndexNow contract fail: workflow must upload distribution evidence.');
const runner = read('scripts/distribution/run_post_publish_distribution.mjs');
for (const token of ['api.indexnow.org/indexnow','webmasters/v3/sites/','searchconsole.googleapis.com/v1/urlInspection/index:inspect','provider_receipt.json','observation_feedback.json','receipts/']) if (!runner.includes(token)) fail(`IndexNow contract fail: post-publish runner missing ${token}.`);
const emit = read('scripts/indexnow_emit.js');
for (const token of ['indexnow-priority.txt','indexnow-batch.txt','indexnow-manifest.json']) if (!emit.includes(token)) fail(`IndexNow contract fail: emit script must write ${token}.`);
const priorityPath = path.join(root, 'reports', 'indexnow-priority.txt');
const batchPath = path.join(root, 'reports', 'indexnow-batch.txt');
if (fs.existsSync(priorityPath) || fs.existsSync(batchPath)) {
  if (!fs.existsSync(priorityPath) || !fs.existsSync(batchPath)) fail('IndexNow contract fail: priority and batch artifacts must exist together.');
  const urls = fs.readFileSync(batchPath, 'utf8').split(/\r?\n/).map((s) => s.trim()).filter(Boolean);
  if (!urls.length) fail('IndexNow contract fail: batch file has no URLs.');
  const invalid = urls.filter((url) => !/^https:\/\/www\.hicksconsulting\.org\//.test(url));
  if (invalid.length) fail(`IndexNow contract fail: non-canonical URLs in batch file: ${invalid.slice(0, 5).join(', ')}`);
}
console.log('IndexNow post-publish distribution contract OK');
