#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
const ROOT=process.cwd(); const APPLY=process.argv.includes('--apply'); const THRESHOLD=.85;
const manifestFile=path.join(ROOT,'data/admin/content_manifest.json'); const redirectsFile=path.join(ROOT,'_redirects');
function read(f){return fs.readFileSync(f,'utf8')} function write(f,v){fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,v)}
function visible(h){return String(h).replace(/<(script|style|header|nav|footer)\b[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim().toLowerCase()}
function tok(v){return String(v).match(/[a-z0-9']+/g)||[]} function freq(a){const m=new Map();for(const x of a)m.set(x,(m.get(x)||0)+1);return m}
function cos(a,b){const A=freq(a),B=freq(b);let d=0,an=0,bn=0;for(const v of A.values())an+=v*v;for(const v of B.values())bn+=v*v;for(const [k,v] of A)d+=v*(B.get(k)||0);return an&&bn?d/(Math.sqrt(an)*Math.sqrt(bn)):0}
function rf(route){return path.join(ROOT,'pages',String(route).replace(/^\/|\/$/g,''),'index.html')}
function title(h){return (h.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||'').replace(/\s+/g,' ').trim()}
const manifest=JSON.parse(read(manifestFile)); const arts=manifest.filter(x=>x.validationPassed===true&&x.status==='published'&&x.contentType==='articles'&&String(x.slug||'').startsWith('/resources/articles/')); const ins=manifest.filter(x=>x.validationPassed===true&&x.status==='published'&&x.contentType==='insights'&&String(x.slug||'').startsWith('/resources/insights/'));
const mappings=[]; for(const i of ins){const parent=arts.filter(a=>String(i.title||'').startsWith(`${a.title}:`)).sort((a,b)=>String(b.title).length-String(a.title).length)[0]; if(!parent)continue; const sf=rf(i.slug),tf=rf(parent.slug); if(!fs.existsSync(sf)||!fs.existsSync(tf))continue; const sh=read(sf),th=read(tf); const sim=cos(tok(visible(sh)),tok(visible(th))); if(sim<THRESHOLD)continue; mappings.push({insightId:i.id,source:i.slug,target:parent.slug,similarity:Number(sim.toFixed(3)),duplicateHtmlTitle:title(sh)===title(th)})} mappings.sort((a,b)=>a.source.localeCompare(b.source));
console.log(JSON.stringify({mode:APPLY?'APPLY':'DRY_RUN',threshold:THRESHOLD,publishedArticles:arts.length,publishedInsights:ins.length,consolidationCount:mappings.length,duplicateHtmlTitleCount:mappings.filter(x=>x.duplicateHtmlTitle).length},null,2));
if(!APPLY)process.exit(0); if(mappings.length!==54)throw new Error(`Expected known 54 qualifying duplicate mappings; found ${mappings.length}. Refusing non-deterministic migration.`);
const ts=new Date().toISOString(), ids=new Set(mappings.map(x=>x.insightId)); for(const x of manifest){if(ids.has(x.id)){x.status='revoked';x.revokedAt=x.revokedAt||ts}} write(manifestFile,JSON.stringify(manifest,null,2)+'\n');
let red=read(redirectsFile).replace(/\n?# BEGIN BING DUPLICATE CONSOLIDATION[\s\S]*?# END BING DUPLICATE CONSOLIDATION\n?/g,'\n').trimEnd(); red+='\n\n# BEGIN BING DUPLICATE CONSOLIDATION\n'+mappings.map(x=>`${x.source} ${x.target} 301`).join('\n')+'\n# END BING DUPLICATE CONSOLIDATION\n'; write(redirectsFile,red);
const report={schemaVersion:'1.0.0',generatedAt:ts,purpose:'Consolidate high-similarity orphaned insight derivatives into parent articles for search index-quality remediation.',similarityThreshold:THRESHOLD,consolidationCount:mappings.length,sitemapChange:'LLM-only routes remain in llms.txt but are excluded from the public search sitemap.',publishingCadenceChanged:false,editorialContentRewritten:false,mappings}; write(path.join(ROOT,'reports/BING_INDEXATION_CONSOLIDATION_REPORT.json'),JSON.stringify(report,null,2)+'\n');
console.log(`APPLIED ${mappings.length} consolidations.`);
